version: '3'
services:
  cypress_test:
    container_name: cypress_test
    image: cypress_compose
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./dockerReports/:/app/cypress/results
      - ./dockerReports/:/app/mochawesome-report
     